name: Build and Release Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Prepare and Build APK
        working-directory: simple_live_app
        run: |
          sed -i 's/signingConfig = signingConfigs.getByName("release")/signingConfig = signingConfigs.getByName("debug")/g' android/app/build.gradle.kts
          sed -i 's/as String/.toString()/g' android/app/build.gradle.kts
          
          flutter pub get
          flutter build apk --release --android-skip-build-dependency-validation

      - name: Create Release and Upload APK
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="android_v$(date -u +'%Y%m%d_%H%M')"
          
          gh release create "$TAG_NAME" \
            --title "自动编译Android版本 $TAG_NAME" \
            --notes "由 GitHub Actions 自动编译生成" \
            simple_live_app/build/app/outputs/flutter-apk/simple_live_android.apk
