name: Build and Release Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Prepare and Build Windows App
        working-directory: simple_live_app
        run: |
          flutter pub get
          flutter config --enable-windows-desktop
          
          if (-not (Test-Path "windows/flutter")) {
              mkdir "windows/flutter"
          }
          Add-Content windows/flutter/generated_plugins.cmake "`nadd_compile_definitions(_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS)"
          
          flutter build windows --release

      - name: Package and Release to GitHub
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $buildDir = "simple_live_app/build/windows/x64/runner/Release"
          $zipPath = "simple_live_windows.zip"
          
          if (-not (Test-Path $buildDir)) {
              Write-Error "找不到编译产出的 Release 目录！"
              exit 1
          }
          
          Compress-Archive -Path "$buildDir\*" -DestinationPath $zipPath -Force
          
          $tagName = "win_v$(Get-Date (Get-Date).ToUniversalTime() -Format 'yyyyMMdd_HHmm')"
          
          gh release create "$tagName" `
            --title "自动编译Windows版 $tagName" `
            --notes "由 GitHub Actions 自动编译生成" `
            $zipPath
