name: Build and Release APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter pub get

      - name: Bypass Android Signing Configurations
        run: |
         
          cd simple_live_app/android/app
                    
          python3 -c "
          with open('build.gradle.kts', 'r') as f:
              content = f.read()
          
         
          content = content.replace('signingConfig = signingConfigs.getByName(\"release\")', 'signingConfig = signingConfigs.getByName(\"debug\")')
         
          content = content.replace('as String', '.toString()')
          
          with open('build.gradle.kts', 'w') as f:
              f.write(content)
          "

      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --android-skip-build-dependency-validation

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.run_number }}"
          name: "自动编译apk v${{ github.run_number }}"
          draft: false
          prerelease: false
          files: simple_live_app/build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
